baseURL: 'https://elc-assess.org'
languageCode: 'en-us'
title: 'Ecological Languaging Competencies Assessment Research Team'
theme: 'minimal'

params:
  description: 'Distinguished scholars specializing in Ecological Languaging Competencies Assessment from leading universities worldwide'
  author: 'ELC Assessment Research Team'
  email: 'info@elc-assess.org'
  domain: 'elc-assess.org'

menu:
  main:
    - name: 'Home'
      url: '/'
      weight: 10
    - name: 'Research Team'
      url: '/team/'
      weight: 20
    - name: 'Research'
      url: '/research/'
      weight: 30
    - name: 'Contact'
      url: '/contact/'
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true